version: '3.8'

services:
  # 1. App (Nuxt 3)
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: obol-nuxt
    expose:
      - "3000"
    environment:
      - NUXT_PUBLIC_API_BASE=http://server:8080 # Comunicação via rede interna
    networks:
      - obol_net
    depends_on:
      - server

  # 2. Server (ElysiaJS no Bun)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: obol-elysia
    environment:
      - POCKETBASE_URL=http://database:8090 # Comunicação interna com o banco
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL:-caio@copland.studio}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD:-sua_senha_forte_aqui}
    networks:
      - obol_net
    depends_on:
      - database

  # 3. Banco de Dados (PocketBase)
  database:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: obol-pocketbase
    expose:
      - "8090" # Portal de Admin acessível em http://localhost:8090/_/
    environment:
      # Variáveis que nosso script de migração vai ler
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL:-caio@copland.studio}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD:-sua_senha_forte_aqui}
    volumes:
      - ./db/pb_data:/pb_data
      - ./db/pb_migrations:/pb_migrations # Aqui vai a nossa magia
    networks:
      - obol_net
    command: ["serve", "--http=0.0.0.0:8090", "--dir=/pb_data", "--migrationsDir=/pb_migrations"]

  # 4. Laboratório de Desenvolvimento (Notas Markdown)
  docs:
    image: zefhemel/silverbullet
    container_name: obol-docs
    expose:
      - "3000" # Acessível via proxy do Coolify
    volumes:
      - ./docs:/space # Seus arquivos .md ficam salvos nesta pasta do projeto
    networks:
      - obol_net

networks:
  obol_net:
    driver: bridge
