FROM node:20-alpine

WORKDIR /app

# Add dependencies
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* bun.lockb* ./
RUN rm -f package-lock.json && npm install

# Command for dev with hot reload
CMD ["npm", "run", "dev"]
